### ISSUE TITLE
Wrong key value for intensity value from psi4

### ISSUE THREAD

**Issue by wtwver** [philipmnel/pyvpt2#35]
The IR_intensities key should be IR_intensity.

https://github.com/philipmnel/pyvpt2/blob/aab6c3e0856bc8e7cd06a1f67fe5bb08ae8229d5/pyvpt2/vpt2.py#L76

There is no IR_intensities key in psi4 repo as shown in 
https://github.com/search?q=repo%3Apsi4%2Fpsi4+IR_intensities&type=code

**Comment by philipmnel** [comment]
Indeed. Thanks for the catch.
